export const musicStyles = [
  {
  id: 1,
  name: 'Rock',
  albums: [
    {
        id: 1,
        name: 'Los Bravos',
        image: require('./scr/img/LosBravos.jpg'),
        singer: 'Los Bravos',
        songs: ['Trapped', 'Baby, Baby', 'Make it Easy for Me', 'She Believes in Me', 'Will You Always Love Me', 'Black is Black', 'Stop That Girl', 'Give Me a Chance', 'Im Cuttin Out', 'Two Kinds of Lovers'],
      },

      {
        id: 2,
        name: 'Sueño Stereo',
        image: require('./scr/img/Sodastereo.jpg'),         
        singer: 'Soda Stereo',     
        mp3: require('./scr/mp3/Discoeterno.mp3'),        
        songs: ['Disco eterno', 'Zoom', 'Ojo de la tormenta', 'Efecto doppler', 'Paseando por Roma', 'Pasos', 'Ángel eléctrico', 'Planta', 'X-Playo', 'Moirè'],
      },
      {
        id: 3,
        name: 'Use your illusion i',
        image: require('./scr/img/Useyourillusioni.jpg'),        
        singer: 'Guns n roses',
        songs: ['Garden of eden', 'Perfect crime', 'Live and let die', 'Double talkin’ jive', 'Dont cry', 'You aint the first ', 'Double talkin jive', 'Bad apples', 'Dead horse', 'Right next door to hell'],
      },

      {
        id: 4,
        name: 'A night at the opera',
        image: require('./scr/img/Anightattheopera.png'),   
        singer: 'Queen',     
        songs: ['Seaside rendezvous', 'God save the queen', 'Lazing on a Sunday afternoon', 'Bohemian rhapsody', 'Love of my life', 'You re my best friend', '39 ', 'Good company', 'Sweet lady', 'Death on two legs'],
      },
      {
        id: 5,
        name: 'The Razors Edge',
        image: require('./scr/img/TheRazorsEdge.jpg'), 
        singer: 'AC/DC',       
        songs: ['Thunderstruck', 'If you want blood', 'Hell aint a bad place to be', 'Let there be rock', 'Have a drink on me', 'Highway to hell', 'T.N.T', 'The razors edge', 'Guns for hire', 'War machine'],
      },
      {
        id: 6,
        name: 'Live at reading',
        image: require('./scr/img/Liveatreading.jpg'),  
        singer: 'Nirvana',
        songs: ['Gimme shelter', 'You got the silver', 'Monkey man', 'Country honk', 'Love in vain', 'Live with me', 'Honky tonk woman', 'Let it bleed', 'Midnight rambler'],
      },
      {
        id: 7,
        name: 'Let it bleed',
        image: require('./scr/img/Letitbleed.jpg'),   
        singer: 'The Rolling Stones',    
        songs: ['Disco eterno', 'Zoom', 'Ojo de la tormenta', 'Efecto doppler', 'Paseando por Roma', 'Pasos', 'Ángel eléctrico', 'Planta', 'X-Playo', 'Moirè'],
      },
      {
        id: 8,
        name: 'The Dark Side Of The Moon',
        image: require('./scr/img/TheDarkSideOfTheMoon.jpeg'), 
        singer: 'Pink Floyd',       
        songs: ['Speak to me / Breathe', 'Time', 'Us and them', ' Eclipse', 'The great gig in the sky', 'Any colour you like', 'Brain damage', 'Money', 'On the run', 'Hey you'],
      },
      {
        id: 9,
        name: 'One More Light',
        image: require('./scr/img/OneMoreLight.jpg'), 
        singer: 'Linkin Park',       
        songs: ['Good goodbye', 'Heavy', 'Battle symphony', 'Sharp edges', 'Invisible', 'Halfway right', ' Sorry for nows', ' Talking to myself', 'Nobody can save me', ''],
      },
      {
        id: 10,
        name: 'Get a Grip',
        image: require('./scr/img/GetaGrip.jpg'),     
        singer: 'Aerosmith',   
        songs: ['Walk on down', 'Crazy', 'Get a grip', 'Boogie man', 'Intro', 'Shut up & dance', 'Amazing', 'Cryin’', 'Fever', 'Line up'],
      },
    ],
  },
  {
    id: 2,
    name: 'Pop',
    albums: [
      {
        id: 1,
        name: 'Please Please Me',
        image: require('./scr/img/PleasePleaseMe.jpg'),
        mp3: require('./scr/mp3/Demons.mp3'),        
        singer: 'The Beatles',        
        songs: ['Misery', 'Anna (Go to Him)', 'Chains', 'Boys', 'Ask Me Why', 'Please Please Me', 'Love Me Do', 'P.S. I Love You', 'Baby Its You', 'Theres a Place'],
      },
      {
        id: 2,
        name: 'Night Visions',
        image: require('./scr/img/NightVisions.jpeg'),
        mp3: 'https://snack-code-uploads.s3.us-west-1.amazonaws.com/~asset/dc1cedc969491f67a0dd19e09d61d9ea',
        singer: 'Imagine Dragons',
        songs: ['Radioactive', 'Tiptoe', 'Its Time', 'Demons', 'On Top of the World', 'Amsterdam', 'Hear Me', 'Every Night', 'Bleeding Out', 'Underdog'],
      },
      {
        id: 3,
        name: 'Music of the Spheres',
        image: require('./scr/img/Musicofthespheres.jpeg'),
        mp3: require('./scr/mp3/Demons.mp3'),        
        singer: 'Coldplay',
        songs: ['Let Somebody Go', 'My Universe', 'Humankind', 'Biutyful', 'People of The Pride', 'Coloratura', 'Higher Power', '*✧', '♡', '∞'],
      },
      {
        id: 4,
        name: 'Love Yourself',
        image: require('./scr/img/LoveYourself.jpg'),
        singer: 'BTS',
        songs: ['IDOL', 'Dimple', 'Magic Shop', 'Her', 'Go Go', 'Anpanman', 'MIC Drop', 'Tear', 'Answer: Love Myself', 'DNA'],
      },
      {
        id: 5,
        name: 'Rebelde',
        image: require('./scr/img/Revelde.jpg'),
        singer: 'RBD',
        songs: ['Fuego', 'Enséñame', 'Un Poco de Tu Amor', 'Santa No Soy', 'Sálvame', 'Sólo Quédate En Silencio', 'Cuando El Amor Se Acaba', 'Rebelde', 'Futuro Ex-Novio', 'Otro Día Que Va'],
      },
      {
        id: 6,
        name: 'Up All Night',
        image: require('./scr/img/TheLastDon2.jpg'),
        singer: 'One Direction',
        songs: ['Stole My Heart', 'I Want', 'Taken', 'I Wish', 'Same Mistakes', 'More Than This', 'Everything About You', 'Tell Me a Lie', 'Stand Up', 'Gotta Be You'],
      },
      {
        id: 7,
        name: 'Backstreets Back',
        image: require('./scr/img/BackstreetBack.jpg'),
        singer: 'Backstreet Boys',
        songs: ['Like a Child', '10,000 Promises', 'All I Have to Give', 'Missing You', 'If I Dont Have You', 'Hey, Mr. DJ', 'Thats the Way I Like It', 'Everybody', 'As Long as You Love Me', 'Thats What She Said'],
      },
      {
        id: 8,
        name: 'V',
        image: require('./scr/img/V.png'),
        singer: 'Maroon 5',
        songs: ['My Heart Is Open', 'Sex and Candy', 'It Was Always You', 'Unkiss Me', 'New Love', 'Animals', 'Shoot Love', 'Maps', 'Feelings', 'Sugar'],
      },
      {
        id: 9,
        name: 'The Album',
        image: require('./scr/img/TheAlbum.jpg'),
        singer: 'Jonas Brothers',
        songs: ['Walls', 'Little Bird', 'Summer in the Hamptons', 'Summer Baby', 'Wings', 'Celebrate!', 'Sail Away', 'Miracle', 'Waffle House', 'Americana'],
      },
      {
        id: 10,
        name: 'AM',
        image: require('./scr/img/AM.jpg'),
        singer: 'Arctic Monkeys',
        songs: ['I Wanna Be Yours', 'One for the Road', 'Mad Sounds', 'Knee Socks', 'Do I Wanna Know?', 'R U Mine?', 'Arabella', 'I Want It All', 'Snap Out of It', 'Fireside'],
      },
    ],
  },
    {
    id: 1,
    name: 'Latina',
    albums: [
      {
        id: 1,
        name: 'Mi sangre',
        image: require('./scr/img/Misangre.jpg'),
        singer: 'Juanes',
        songs: ['La Camisa Negra', 'Sueños', 'Volverte A Ver', '¿Qué Pasa?', 'Dámelo', 'Tu Guardián', 'Ámame', 'Para Tu Amor', 'No Siento Penas', 'Rosario Tijeras'],
      },
      {
        id: 2,
        name: 'Sigo siendo yo',
        image: require('./scr/img/Sigosiendoyo.jpg'),
        singer: 'Marc Anthony',
        songs: ['No me ames', 'Celos', '¿Ahora quién?', 'Lo que no di', 'Valió la pena', 'Tu amor me hace bien', 'Barco a la deriva', 'Se esfuma tu amor', 'Tragedia', 'Da la vuelta'],
      },
      {
        id: 3,
        name: 'Jovem Guarda',
        image: require('./scr/img/JovemGuarda.jpg'),
        singer: 'Roberto Carlos',
        songs: ['Gosto do jeitinho dela', 'Lobo mau (The Wanderer)', 'Mexerico da Candinha', 'Coimbra', 'Não é papo pra mim', 'O velho homem do mar', 'Sorrindo para mim', 'Pega ladrão', 'O feio', 'Eu te adoro meu amor'],
      },
      {
        id: 4,
        name: 'Euphoria',
        image: require('./scr/img/Euphoria.jpg'),
        singer: 'Enrique Iglesias',
        songs: ['One Day at a Time', 'Heartbeat', 'Dirty Dancer', 'Why Not Me?', 'I Like It', 'Heartbreaker', 'Dile que', 'No me digas que no', 'Ayer', 'Tú y yo'],
      },
      {
        id: 5,
        name: 'Selena',
        image: require('./scr/img/Selena.jpg'),
        singer: 'Selena',
        songs: ['One More Time', 'Oldies Medley', 'A Boy Like That', 'Is It The Beat?', 'Viviras Selena', 'Disco Medley', 'Cumbia Medley', 'Only Love', 'I Could Fall In Love', 'Dreaming Of You'],
      },
      {
        id: 6,
        name: 'Soplando',
        image: require('./scr/img/Soplando.jpg'),
        singer: 'Juan Luis GuerraSoplando',
        songs: ['Loreta', 'Sambomba', 'Carnaval', 'Feliciana', 'La Calle Gris', 'Soplando', 'Juana Mecho', 'Jardinera', 'Frio Frio', 'Areito'],
      },
      {
        id: 7,
        name: 'Viviendo deprisa',
        image: require('./scr/img/Viviendodeprisa.jpg'),
        singer: 'Alejandro Sanz',
        songs: ['Los dos cogidos de la mano', 'Todo sigue igual', 'Se le apagó la luz', 'Completamente loca', 'Pisando fuerte', 'Lo que fui es lo que soy', 'Duelo al amanecer', 'Toca para mí', 'Es este amor', 'Viviendo deprisa'],
      },
      {
        id: 8,
        name: 'The Last Don 2',
        image: require('./scr/img/TheLastDon2.jpg'),
        singer: 'Don Omar',
        songs: ['Yo soy de aquí', 'Dobla rodilla', 'Callejero', 'Olvidar Que Somos Amigos', 'En lo oscuro', 'Sandunga', 'Tírate al medio', 'Perdido en tus ojos', 'Guaya guaya', 'Soledad'],
      },
      {
        id: 9,
        name: 'Paso a paso',
        image: require('./scr/img/Pasoapaso.jpg'),
        singer: 'Luis Fonsi',
        songs: ['Estoy Perdido', 'Nada Es Para Siempre', 'Arropame', 'Escondido', 'Vivo Muriendo', 'Para Mi', 'Por Una Mujer', 'Me Matas', 'Me Lo Dice El Alma', 'Paso A Paso'],
      },
      {
        id: 10,
         name: 'Barrio fino',
        image: require('./scr/img/Barriofino.jpg'),
        singer: 'Daddy Yankee',
        songs: ['Sabor a melao', 'No Me Dejes Solo', 'Golpe De Estado', 'Tu Principe', 'El Empuje', 'King Daddy', 'Santifica Tus Escapularios', 'Lo que pasó, pasó', 'Saber Su Nombre', 'Salud y vida'],
      },
    ],
  },
];
